require 'ruby_trains/trip_calculator'
require 'ruby_trains/connection'
require 'ruby_trains/network'
require 'ruby_trains/station'
require 'ruby_trains/validator'
require 'ruby_trains/version'
require 'ruby_trains/cli'
