# This is where you can overwrite RuboCop rules.
# If its checking is too verbose or annoying
# Refer to https://github.com/bbatsov/rubocop/blob/master/config/default.yml
Metrics/LineLength:
  Max: 140

Style/FrozenStringLiteralComment:
    Enabled: false

Style/EmptyLinesAroundBlockBody:
  Enabled: false

# Test modules will probably be large
Metrics/ModuleLength:
  Enabled: false
